import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import {
  ArrowRight,
  Bell,
  BellOff,
  BookOpen,
  BrainCircuit,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCheck,
  CircleAlert,
  CircleCheck,
  ChevronDown,
  Clock,
  Clock3,
  Code as CodeIcon,
  Crown,
  Cpu,
  Database,
  Download,
  FileChartColumn,
  Globe,
  GraduationCap,
  Info as InfoIcon,
  LayoutTemplate,
  Loader,
  LogOut,
  Lock,
  LucideAngularModule,
  Map as MapIcon,
  MonitorOff,
  PencilLine,
  Plus,
  RefreshCw,
  Save,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Send,
  TriangleAlert,
  Users,
  WandSparkles,
  X,
  XCircle,
} from 'lucide-angular';
import { appRoutes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideHttpClient(),
    provideRouter(appRoutes),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowRight,
        Bell,
        BellOff,
        BookOpen,
        BrainCircuit,
        Building2,
        Calendar,
        CalendarClock,
        Check,
        CheckCheck,
        CircleAlert,
        CircleCheck,
        ChevronDown,
        Clock,
        Clock3,
        CodeIcon,
        Crown,
        Cpu,
        Database,
        Download,
        FileChartColumn,
        Globe,
        GraduationCap,
        InfoIcon,
        LayoutTemplate,
        Loader,
        LogOut,
        Lock,
        MapIcon,
        MonitorOff,
        PencilLine,
        Plus,
        RefreshCw,
        Save,
        Search,
        Server,
        Settings,
        ShieldCheck,
        Send,
        TriangleAlert,
        Users,
        WandSparkles,
        X,
        XCircle,
      })
    ),
  ]
};
