import {
  ArrowRight,
  Bell,
  BrainCircuit,
  Building2,
  Calendar,
  Check,
  CheckCheck,
  ChevronDown,
  CircleAlert,
  CircleCheck,
  CircleX,
  Clock3,
  Code,
  Cpu,
  Database,
  Download,
  Globe,
  GraduationCap,
  Info,
  LayoutTemplate,
  LogOut,
  Map,
  Menu,
  PencilLine,
  Plus,
  RefreshCw,
  Save,
  Search,
  Server,
  ShieldCheck,
  Users,
  WandSparkles,
} from 'lucide-angular';

export const APP_ICONS = {
  map: Map,
  check: Check,
  clock3: Clock3,
  circleAlert: CircleAlert,
  code: Code,
  cpu: Cpu,
  layoutTemplate: LayoutTemplate,
  database: Database,
  shieldCheck: ShieldCheck,
  brainCircuit: BrainCircuit,
  info: Info,
  xCircle: CircleX,
  checkCheck: CheckCheck,
  search: Search,
  plus: Plus,
  pencilLine: PencilLine,
  wandSparkles: WandSparkles,
  arrowRight: ArrowRight,
  download: Download,
  building2: Building2,
  users: Users,
  chevronDown: ChevronDown,
  calendar: Calendar,
  refreshCw: RefreshCw,
  circleCheck: CircleCheck,
  save: Save,
  server: Server,
  globe: Globe,
  bell: Bell,
  logOut: LogOut,
  graduationCap: GraduationCap,
  menu: Menu,
} as const;

export type AppIconKey = keyof typeof APP_ICONS;
