import {
  ArrowRight,
  Bell,
  BellOff,
  BookOpen,
  BrainCircuit,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCheck,
  CircleAlert,
  CircleCheck,
  ChevronDown,
  Clock,
  Clock3,
  Code as CodeIcon,
  Crown,
  Cpu,
  Database,
  Download,
  FileChartColumn,
  Globe,
  GraduationCap,
  Info as InfoIcon,
  LayoutTemplate,
  Loader,
  LogOut,
  Lock,
  Map as MapIcon,
  MonitorOff,
  PencilLine,
  Plus,
  RefreshCw,
  Save,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Send,
  TriangleAlert,
  Users,
  WandSparkles,
  X,
  XCircle,
} from 'lucide-angular';

export const APP_ICONS = {
  arrowRight: ArrowRight,
  bell: Bell,
  bellOff: BellOff,
  bookOpen: BookOpen,
  brainCircuit: BrainCircuit,
  building2: Building2,
  calendar: Calendar,
  calendarClock: CalendarClock,
  check: Check,
  checkCheck: CheckCheck,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  chevronDown: ChevronDown,
  clock: Clock,
  clock3: Clock3,
  code: CodeIcon,
  crown: Crown,
  cpu: Cpu,
  database: Database,
  download: Download,
  fileChartColumn: FileChartColumn,
  globe: Globe,
  graduationCap: GraduationCap,
  info: InfoIcon,
  layoutTemplate: LayoutTemplate,
  loader: Loader,
  logOut: LogOut,
  lock: Lock,
  map: MapIcon,
  monitorOff: MonitorOff,
  pencilLine: PencilLine,
  plus: Plus,
  refreshCw: RefreshCw,
  save: Save,
  search: Search,
  server: Server,
  settings: Settings,
  shieldCheck: ShieldCheck,
  send: Send,
  triangleAlert: TriangleAlert,
  users: Users,
  wandSparkles: WandSparkles,
  x: X,
  xCircle: XCircle,
} as const;

export type AppIconKey = keyof typeof APP_ICONS;
