import {
  ArrowRight,
  Bell,
  BellOff,
  BrainCircuit,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  Clock3,
  Code,
  Crown,
  Cpu,
  Database,
  Download,
  ExternalLink,
  FileText,
  Globe,
  GraduationCap,
  Inbox,
  Info,
  LayoutTemplate,
  LucideIconData,
  Loader,
  Lock,
  LogOut,
  Map,
  Menu,
  PencilLine,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Server,
  ShieldCheck,
  Trash2,
  TriangleAlert,
  UploadCloud,
  Users,
  WandSparkles,
  X,
} from 'lucide-angular';

export const APP_ICONS: Record<string, LucideIconData> = {
  map: Map,
  check: Check,
  clock3: Clock3,
  circleAlert: CircleAlert,
  code: Code,
  cpu: Cpu,
  layoutTemplate: LayoutTemplate,
  database: Database,
  shieldCheck: ShieldCheck,
  brainCircuit: BrainCircuit,
  info: Info,
  xCircle: CircleX,
  checkCheck: CheckCheck,
  search: Search,
  plus: Plus,
  pencilLine: PencilLine,
  wandSparkles: WandSparkles,
  arrowRight: ArrowRight,
  download: Download,
  building2: Building2,
  users: Users,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  calendar: Calendar,
  refreshCw: RefreshCw,
  circleCheck: CircleCheck,
  save: Save,
  server: Server,
  globe: Globe,
  bell: Bell,
  bellOff: BellOff,
  logOut: LogOut,
  graduationCap: GraduationCap,
  calendarClock: CalendarClock,
  menu: Menu,
  trash2: Trash2,
  triangleAlert: TriangleAlert,
  loader: Loader,
  crown: Crown,
  lock: Lock,
  send: Send,
  x: X,
  externalLink: ExternalLink,
  fileText: FileText,
  uploadCloud: UploadCloud,
  inbox: Inbox,
};

export type AppIconKey = keyof typeof APP_ICONS;
